version: "3.9"

services:

  # demo:
  #   image: mirroronline
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./data/demo:/ag4/data

  prod:
    build: ./
    image: mirroronline:latest
    container_name: mirroronline
    ports:
      - "8001:8000"
    volumes:
      - ./data:/ag4/data
