version: "3.9"

services:

  demo:
    image: fakebook
    ports:
      - "8000:8000"
    volumes:
      - ./data/demo:/fakebook/data

  prod:
    image: fakebook
    ports:
      - "8001:8000"
    volumes:
      - ./data/prod:/fakebook/data
