# Generated by Django 5.1.4 on 2024-12-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_answer_id_alter_question_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Experiment Terms and Conditions", max_length=200
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        help_text="Upload the terms and conditions PDF.",
                        upload_to="documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
