# Generated by Django 5.1.4 on 2024-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_consent_delete_experimentdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="identifier",
            field=models.CharField(
                choices=[
                    ("end_experiment_header_de", "End Experiment Header (German)"),
                    ("end_experiment_header_en", "End Experiment Header (English)"),
                    ("end_experiment_message_de", "End Experiment Message (German)"),
                    ("end_experiment_message_en", "End Experiment Message (English)"),
                    ("participant_info_de", "Participant Information (German)"),
                    ("participant_info_en", "Participant Information (English)"),
                    ("consent_form_de", "Consent Form (German)"),
                    ("consent_form_en", "Consent Form (English)"),
                ],
                help_text="Choose which text to display.",
                max_length=200,
                unique=True,
            ),
        ),
    ]
