# Generated by Django 5.1.4 on 2024-12-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_alter_text_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="visibility",
            field=models.BooleanField(default=False),
        ),
    ]
