# Generated by Django 5.1.4 on 2024-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_alter_text_content_alter_text_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_duration",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text="Maximale Zeit in Sekunden, bevor der Benutzer automatisch ausgeloggt wird.",
                    ),
                ),
            ],
        ),
    ]
