# Generated by Django 5.1.4 on 2024-12-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0012_sessionconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sub_questions",
            field=models.TextField(
                blank=True,
                help_text="Komma-separierte Sub-Fragen für Formate wie Multiple Likert oder Fancy Combination.",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("likert", "Likert Scale"),
                    ("multiple_choice", "Multiple Choice"),
                    ("single_choice", "Single Choice"),
                    ("numeric", "Numeric Scale"),
                    ("open_text", "Open Text"),
                    ("slider", "Slider"),
                    ("multiple_likert", "Multiple Likert"),
                    ("fancy_combination", "Fancy Combination"),
                ],
                help_text="Der Typ der Frage.",
                max_length=20,
            ),
        ),
    ]
