# Generated by Django 5.1.4 on 2024-12-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0016_alter_question_choices_alter_question_max_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sub_choices",
            field=models.TextField(
                blank=True,
                help_text="Zeilenweise Aussagen für die Matrix-Frage, Semikolon-separierte Sub-Choices.",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="Für alle Fragen mit vordefinierten Antworten: Semikolon-separierte Auswahlmöglichkeiten.",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sub_questions",
            field=models.TextField(
                blank=True,
                help_text="Für Multiple Likert und Fancy Combination: Semikolon-separierte Sub-Fragen.",
            ),
        ),
    ]
