# Generated by Django 5.1.4 on 2024-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0018_sessionconfig_is_timer_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionconfig",
            name="is_timer_enabled",
            field=models.BooleanField(
                default=False, help_text="Timer aktivieren oder deaktivieren"
            ),
        ),
    ]
