# Generated by Django 3.0.5 on 2025-01-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20250123_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionConfig',
        ),
    ]
