# Generated by Django 3.0.5 on 2025-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_delete_sessionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sub_question',
            field=models.CharField(blank=True, help_text='Optional: Sub-question identifier for formats like Multiple Likert.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('numeric', 'Numeric Scale'), ('open_text', 'Open Text'), ('slider', 'Slider'), ('multiple_likert', 'Multiple Likert'), ('ampel_rating', 'Ampel Rating')], help_text='Hier bitte den Fragen-Typ festlegen.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_questions',
            field=models.TextField(blank=True, help_text='Für Multiple Likert: Semikolon-separierte Sub-Fragen.'),
        ),
    ]
