# Generated by Django 3.0.5 on 2025-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20250123_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Für alle Fragetypen mit <strong>vordefinierten Choices</strong>. <br> Dropdown, Multiple/Single Choice, Likert, Multiple Likert, Slider.<br> Für Slider: Bitte genau drei Möglichkeiten passend zu den Min und Max Werten angeben. <br>Angabe: Semikolon-separierte Auswahlmöglichkeiten.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], help_text='Für alle Fragetypen: Gibt an, ob die Frage vor oder nach dem Experiment gestellt wird.', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_value',
            field=models.IntegerField(blank=True, help_text=' <strong>Für Numeric Scale und Slider: </strong> Maximaler Wert.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_value',
            field=models.IntegerField(blank=True, help_text=' <strong>Für Numeric Scale und Slider: </strong> Minimaler Wert.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(blank=True, help_text="Für alle Fragetypen: Hier bitte den Item-Name festlegen (Spalte 'name' in der questions Datenbanktabelle)."),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Für alle Fragetypen: Welche Frage soll in diesem Item gestellt werden?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('numeric', 'Numeric Scale'), ('open_text', 'Open Text'), ('slider', 'Slider'), ('multiple_likert', 'Multiple Likert'), ('ampel_rating', 'Ampel Rating')], help_text='Für alle Fragetypen: Hier bitte den Fragen-Typ auswählen.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='start_value',
            field=models.IntegerField(blank=True, help_text=' <strong>Für Slider: </strong> Startwert. Bitte Wert im Bereich von Min und Max Value wählen.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='step_value',
            field=models.IntegerField(blank=True, help_text=' <strong>Für Slider: </strong> Stepgröße.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_choices',
            field=models.TextField(blank=True, help_text=' <strong>NUR für Ampel-Frage. </strong><br>Angabe von Tupeln für Fragenpole als semikolon-separierte Sub-Choices. <br>Beispieltext: negativ;positiv;ineffektiv;effektiv'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_questions',
            field=models.TextField(blank=True, help_text=' <strong>NUR für Multiple Likert.</strong> <br>Angabe: Semikolon-separierte Sub-Fragen.'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(help_text="HTML text sorgt dafür, dass der Content deutlich besser lesbar ist. Hierfür einfach den Plain Text in ChatGPT o.Ä. einfügen mit dem Prompt <br>'Erstelle eine anschauliche HTML-Seite mit folgendem Plaintext: [<i>Text hier einfügen</i>] <br>Der Titel der Seite sollte [<i>Titel</i>] lauten. Der Haupttext soll in der Mitte der Seite stehen, mit einer roten Überschrift und einer Beschreibung darunter. <br>Füge auch eine Kontaktmöglichkeit per E-Mail hinzu. Die Seite soll ansprechend und responsiv gestaltet sein.'"),
        ),
        migrations.AlterField(
            model_name='text',
            name='identifier',
            field=models.CharField(choices=[('end_experiment_header_de', 'End Experiment Header (German)'), ('end_experiment_header_en', 'End Experiment Header (English)'), ('end_experiment_message_de', 'End Experiment Message (German)'), ('end_experiment_message_en', 'End Experiment Message (English)'), ('participant_info_header_de', 'Participant Information Header (German)'), ('participant_info_header_en', 'Participant Information Header (English)'), ('participant_info_message_de', 'Participant Information Message (German)'), ('participant_info_message_en', 'Participant Information Message (English)'), ('consent_form_header_de', 'Consent Form Header (German)'), ('consent_form_header_en', 'Consent Form Header (English)'), ('consent_form_message_de', 'Consent Form Message (German)'), ('consent_form_message_en', 'Consent Form Message (English)'), ('no_consent_message_de', 'No Consent (German)'), ('no_consent_message_en', 'No Consent (English)')], help_text='Textart auswählen.', max_length=200, unique=True),
        ),
    ]
