# Generated by Django 3.0.5 on 2025-01-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20250125_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Anzeigeposition der Frage. Fragen mit niedrigeren Werten erscheinen zuerst.'),
        ),
    ]
