# Generated by Django 3.0.5 on 2025-01-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20250126_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(help_text="HTML Text sorgt dafür, dass der Content deutlich besser lesbar ist. Hierfür einfach den Plain Text in ChatGPT o.Ä. einfügen mit dem Prompt <br>'Erstelle eine anschauliche HTML-Seite mit folgendem Plaintext: [<i>Text hier einfügen</i>] <br>Der Titel der Seite sollte [<i>Titel</i>] lauten. Der Haupttext soll in der Mitte der Seite stehen, mit einer roten Überschrift und einer Beschreibung darunter. <br>Füge auch eine Kontaktmöglichkeit per E-Mail hinzu. Die Seite soll ansprechend und responsiv gestaltet sein.'"),
        ),
    ]
