# Generated by Django 3.0.5 on 2025-01-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20250128_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='range_values',
            field=models.CharField(blank=True, help_text="Geben Sie die Werte für die Range ein, getrennt durch Semikolons (z. B. '0;1;2;3;4;5;6;7;8;9;10').", max_length=100, null=True),
        ),
    ]
