# Generated by Django 3.0.5 on 2025-01-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_question_range_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='range_values',
            new_name='range_value',
        ),
    ]
