# Generated by Django 3.0.5 on 2025-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_auto_20250129_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='range_value',
            field=models.CharField(blank=True, help_text="<strong>NUR für Ampel-Frage. </strong>Geben Sie die Werte für die Range ein, getrennt durch Semikolons (z. B. '0;1;2;3;4;5;6;7;8;9;10').", max_length=100, null=True),
        ),
    ]
