# Generated by Django 3.0.5 on 2024-11-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20241119_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
