# Generated by Django 3.0.5 on 2025-01-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_tag_newspaper_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(default='Control', max_length=50),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='tag',
            field=models.CharField(default='Control', max_length=50),
        ),
    ]
