# Generated by Django 3.0.5 on 2025-01-24 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20250123_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(upload_to='articles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
