# Generated by Django 3.0.5 on 2025-01-25 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20250124_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='content',
            field=models.CharField(default='This is the short description of the newspaper content.', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='Format am besten einheitlich. Empfehlung Bannerformat:1800 x 600 px', upload_to='articles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(help_text='Format am besten einheitlich. Empfehlung Format:900 x 600 px', upload_to='articles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
