# Generated by Django 3.0.5 on 2025-01-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20250125_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='content',
            field=models.CharField(default='Change me: This is the short description of the newspaper content.', max_length=255),
        ),
    ]
