# Generated by Django 3.0.5 on 2025-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20250126_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
