# Generated by Django 3.0.5 on 2025-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20250130_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='Ein eindeutiger, URL-freundlicher Text, der zum Titel passt. Zum Beispiel: rationalist-1 wenn die Zeitung Rationalist heißt.', unique=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='content',
            field=models.CharField(default='Ändere mich: Kurzbeschreibung der Zeitung', max_length=255),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='id',
            field=models.IntegerField(help_text='Zahlenwert der für Zuordnung von Artikeln verwendet wird.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(default='Ändere mich: Titel der Zeitung', max_length=255),
        ),
    ]
