# Generated by Django 3.0.5 on 2024-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20241206_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='condition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
