# Generated by Django 5.1.4 on 2025-01-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_experimentcondition"),
        ("profiles", "0008_alter_profile_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="condition_id",
        ),
        migrations.AddField(
            model_name="profile",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.experimentcondition",
            ),
        ),
    ]
