# Generated by Django 3.0.5 on 2024-11-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_configuration_comments_friends_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='chat_friends_only',
            new_name='comments_interaction',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='chat_enabled',
            new_name='like_dislike_enabled',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='comments_friends_only',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='posts_friends_only',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='profiles_friends_only',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='relationship_management_enabled',
        ),
    ]
