# Generated by Django 3.0.5 on 2024-12-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20241128_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='relationship_management_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
