# Generated by Django 5.1.4 on 2025-01-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0012_alter_configuration_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="relationship_management_enabled",
        ),
    ]
