# Generated by Django 3.0.5 on 2025-01-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_auto_20250123_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='comments_enabled',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='comments_interaction',
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_timer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='max_session_duration',
            field=models.PositiveIntegerField(default=3600),
        ),
    ]
