# Generated by Django 3.0.5 on 2025-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_usereventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
