# Generated by Django 5.1.4 on 2025-01-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_alter_trackedsession_id_alter_usereventlog_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrackedSession",
        ),
    ]
