# Generated by Django 5.1.4 on 2025-01-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_delete_trackedsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="usereventlog",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
