# Generated by Django 5.1.4 on 2025-01-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0010_usereventlog_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usereventlog",
            name="duration",
        ),
    ]
