# Generated by Django 5.1.4 on 2025-01-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_usercontentposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("tag", models.CharField(default="control", max_length=50)),
            ],
        ),
    ]
