# Generated by Django 5.1.4 on 2025-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_experimentcondition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentcondition",
            name="tag",
            field=models.CharField(max_length=50),
        ),
    ]
