# Generated by Django 3.0.5 on 2025-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_auto_20250123_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentcondition',
            name='description',
            field=models.TextField(blank=True, help_text='Eine detaillierte Beschreibung der Bedingung. Dieses Feld ist optional.'),
        ),
        migrations.AlterField(
            model_name='experimentcondition',
            name='name',
            field=models.CharField(help_text="Der Name der Bedingung (z.B. 'Kontrolle', 'Experimentell'). Maximale Länge beträgt 100 Zeichen.", max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentcondition',
            name='tag',
            field=models.CharField(help_text="Ein kurzer Tag zur Identifizierung der Bedingung (z.B. 'exp' für experimentell, 'control' für Kontrolle). Wird auch für die Zuordnung von Inhalten (Zeitungen, Artikel, Kommentare) verwendet.", max_length=50),
        ),
    ]
