# Generated by Django 3.0.5 on 2024-12-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20241204_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
