# Generated by Django 3.0.5 on 2025-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20241219_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
