# Generated by Django 5.1.4 on 2025-01-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0010_alter_comment_id_alter_dislike_id_alter_like_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tag",
            field=models.CharField(default="control", max_length=50),
        ),
    ]
