# Generated by Django 3.0.5 on 2025-01-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20250123_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
