# Generated by Django 3.0.5 on 2025-01-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_auto_20250124_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='condition_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='public',
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Muss öffentlich sein, um VPN angezeigt zu werden.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Optionale Zuordnung zu Versuchsbedingung', max_length=50),
        ),
    ]
