# Generated by Django 3.0.5 on 2025-01-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20250123_1026'),
        ('articles', '0016_auto_20250130_1059'),
        ('comments', '0015_auto_20250130_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(help_text='Zuordnung zu Artikel', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Autor/in des Kommentars', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='disliked',
            field=models.ManyToManyField(blank=True, help_text='Nur möglich für Primärkommentare.', related_name='disliked_comments_set', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Muss öffentlich sein, um der Versuchsperson angezeigt zu werden.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_secondary',
            field=models.BooleanField(default=False, help_text='Gibt an, ob der Kommentar ein Sekundärkommentar ist'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(blank=True, help_text='Nur möglich für Primärkommentare.', related_name='liked_comments_set', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='<strong>Wichtig!</strong> Muss ein Hauptkommentar sein, der zum oben ausgewählten Artikel zugeordnet ist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.Comment'),
        ),
    ]
