openapi: 3.0.0
info:
  title: Mirronline Management API
  version: 1.0.0

servers:
  - url: http://127.0.0.1:8000

components:
  securitySchemes:
    apikeyAuth:
      type: http
      scheme: apikey

security:
  - apikeyAuth: []

paths:
  /api/profile/comment/:
    post:
      tags:
        - comment
      summary: Create a new comment.
      description: Create a comment for a specific article.
      parameters:
        - name: profile_id
          in: query
          schema:
            type: integer
          required: true
          description: ID of the author (profile).
          example: 1
        - name: article_id
          in: query
          schema:
            type: integer
          required: true
          description: ID of the article.
          example: 42
        - name: parent_comment_id
          in: query
          schema:
            type: integer
          required: false
          description: ID of the parent comment for replies (optional).
          example: 10
        - name: public
          in: query
          schema:
            type: boolean
          required: true
          description: Is the comment visible for all users?
          example: 10
        - name: condition_id
          in: query
          schema:
            type: integer
          required: false
          description: Experimental condition
          example: 10
        - name: content
          in: query
          schema:
            type: string
          required: true
          description: The content of the comment.
          example: "This is a sample comment."
      responses:
        "201":
          description: Successful comment creation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Comment created successfully"
                  comment_id:
                    type: integer
                    example: 123
        "400":
          description: Bad request - Missing or invalid fields.
        "404":
          description: Resource not found - Profile or article does not exist.

    delete:
      tags:
        - comment
      summary: Delete a comment.
      description: Deletes an existing comment by ID.
      parameters:
        - name: comment_id
          in: query
          schema:
            type: integer
          required: true
          description: ID of the comment to delete.
          example: 123
      responses:
        "200":
          description: Successful comment deletion.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Comment deleted successfully"
        "400":
          description: Bad request - Missing or invalid comment ID.
        "404":
          description: Comment not found.

  /api/user:
    post:
      tags:
        - default
      summary: Creates a new user and associated profile.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      parameters:
        - name: username
          in: query
          schema:
            type: string
          description: The username of the user.
          example: Matella
        - name: password
          in: query
          schema:
            type: string
          description: The password of the user.
          example: test
        - name: email
          in: query
          schema:
            type: string
          description: The email of the user.
          example: matella@example.com
      responses:
        "200":
          description: Successful response.
          content:
            application/json: {}

  /api/profile/relationship:
    post:
      tags:
        - default
      summary: Creates a new relationship between two profiles.
      parameters:
        - name: profileId1
          in: query
          schema:
            type: integer
          description: First profile ID.
          example: 1
        - name: profileId2
          in: query
          schema:
            type: integer
          description: Second profile ID.
          example: 9
      responses:
        "200":
          description: Successful response.
          content:
            application/json: {}

    delete:
      tags:
        - default
      summary: Deletes a relationship between two profiles.
      parameters:
        - name: profileId1
          in: query
          schema:
            type: integer
          required: true
          description: First profile ID.
          example: 1
        - name: profileId2
          in: query
          schema:
            type: integer
          required: true
          description: Second profile ID.
          example: 9
      responses:
        "200":
          description: Successful response.
          content:
            application/json: {}

  /api/profile/post:
    post:
      tags:
        - default
      summary: Creates a new post.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The text content of the post.
      parameters:
        - name: profileId
          in: query
          schema:
            type: integer
          description: Profile ID of the author.
          example: 15
      responses:
        "200":
          description: Successful response.
          content:
            application/json: {}

    delete:
      tags:
        - default
      summary: Deletes a post.
      parameters:
        - name: postId
          in: query
          schema:
            type: integer
          required: true
          description: Post ID to be deleted.
          example: 18
      responses:
        "200":
          description: Successful response.
          content:
            application/json: {}

  /api/advertisement:
    post:
      tags:
        - default
      summary: Creates a new advertisement.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: Advertisement image.
      parameters:
        - name: text
          in: query
          schema:
            type: string
          description: Text content of the advertisement.
          example: "This is the advertisement text."
      responses:
        "200":
          description: Successful response.
          content:
            application/json: {}

    delete:
      tags:
        - default
      summary: Deletes an advertisement.
      parameters:
        - name: adId
          in: query
          schema:
            type: integer
          required: true
          description: Advertisement ID to be deleted.
          example: 4
      responses:
        "200":
          description: Successful response.
          content:
            application/json: {}
